## Değişken Dönüşümleri

<font color=green>
    
**Udemy - (50 Saat) Python A-Z™: Veri Bilimi ve Machine Learning**

Bölüm 8 - Veri Ön İşleme - Vahit Keskin anlattı. 
    
    247. Değişken Dönüşümleri
    248. One-Hot Dönüşümü ve Dummy Değişken Tuzağı
    249. Veri Standardizasyonu - Dönüşümü
</font>

### İçindekiler

**Giriş**

**Sayısal Değişkenler için Değişken Dönüşümü**

- Binarize Dönüşüm (0-1)

- Sürekli Değişkeni Kategorik Değişkene Çevirme

**Kategorik Değişkenler için Değişken Dönüşümü**

- İki Sınıflı Dönüşüm (1-0)

- Çok Sınıflı Dönüşüm (1 ve Diğerleri (0))

- Çok Sınıflı Dönüşüm (Her bir sınıfa nümerik değer atama)

- One-Hot Encoding (Her bir sınıf için yeni değişkenler oluşturma)

### <font color=blue>**Giriş**</font>

Değişken dönüştürmek ise dönüştürülen bir değişkenin taşıdığı bilginin taşındığı şekliyle kalmaması, dönüştürülmesi demektir. Örneğin cinsiyet değişkenini düşünelim kadın, erkek şeklinde. Bunu bir dönüştürme işlemine soktuğumuzda ve bunlara 0-1 dediğimizde yapı değişmiş olacak tamamen. Veya örneğin elimizde bir yaş değişkeni olsun. Bu yaş değişkeninde 0 yaş ile 10 yaş arasındakileri çocuk olarak veya 1 sınıfı olarak değiştir, 10 yaş ile 20 yaş arasını genç olarak değiştir gibi bir dönüşüm yapmak istediğimizde normalde yaşın içerisinde bulunan değişim yapısını tamamen bozmuş oluyoruz. Normalde 0 ile 80 arasındaki değerlerden oluşuyorsa bu yaş değişkeni bu günün sonunda 1-2-3-4-5 gibi ya da çocuk, yaşlı, genç vb. gibi sınıflara ayrılmış oluyor. Bu da değişkeni dönüştürmektir. 

Dolayısıyla dönüştürme işleminde veri setinin taşımış olduğu bilgiyi bazen bozmuş, bazen de temsil şeklinde değiştirmiş oluyoruz. 

In [1]:
import seaborn as sns
df = sns. load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Bu veri setindeki bazı değişkenlere bazı dönüşümleri uygulamış olacağız.

### Sayısal Değişkenler için Değişken Dönüşümü

Data setinde belirli bir eşik değerinin altındakileri 0 yap üstündekileri 1 yap dediğimizde bu dönüşüm değişkenin standartlaştırılması değil değişkenin dönüştürülmesi işlemidir ve taşımış olduğu bilgiyi etkilemektedir. 

#### <font color=green>Binarize Dönüşüm (0-1)</font>

In [10]:
import numpy as np
import pandas as pd

V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])
df = pd.DataFrame({"V1" : V1,
                   "V2" : V2,
                   "V3" : V3})
df = df.astype(float)
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [11]:
from sklearn import preprocessing

In [12]:
binarizer = preprocessing.Binarizer(threshold = 5).fit(df)

In [13]:
binarizer.transform(df)

array([[0., 1., 1.],
       [0., 1., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 1.]])

*5 ve 5'in altındakilere 0, üstündekilere 1 demiş olduk.*

#### <font color=green>Sürekli Değişkeni Kategorik Değişkene Çevirme</font>

In [53]:
import seaborn as sns
df = sns. load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Buradaki "total_bill", "tip", "size" sürekli değişkenlerini kategorik değişkene dönüştürmek istediğimizi düşünelim. Ve örneğin birisini 3 sınıfına birisini 2 sınıfa diğerini de 2 sınıfa falan ayırmak istediğimizi düşünelim.

Öncelikle sürekli değişkenleri belirlememiz gerekiyor fonksiyona verebilmek için.

In [54]:
dff = df.select_dtypes(include = ["float64", "int64"])

In [55]:
dff.head()

total_bill   tip  size
0       16.99  1.01     2
1       10.34  1.66     3
2       21.01  3.50     3
3       23.68  3.31     2
4       24.59  3.61     4

In [57]:
from sklearn import preprocessing

est = preprocessing.KBinsDiscretizer(n_bins = [3,2,2], 
                                     encode = "ordinal", 
                                     strategy = "quantile").fit(dff)

In [63]:
array_tr = est.transform(dff)[0:10] # ilk 10 satır için yaptık
array_tr

array([[1., 0., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

In [68]:
val_names = list(dff)
val_names

['total_bill', 'tip', 'size']

In [69]:
pd.DataFrame(array_tr, columns = val_names)

total_bill  tip  size
0         1.0  0.0   1.0
1         0.0  0.0   1.0
2         2.0  1.0   1.0
3         2.0  1.0   1.0
4         2.0  1.0   1.0
5         2.0  1.0   1.0
6         0.0  0.0   1.0
7         2.0  1.0   1.0
8         1.0  0.0   1.0
9         0.0  1.0   1.0

Şu anda elimizdeki sürekli değişkenleri vermiş olduğumuz bins ayarlarına göre `n_bins = [3,2,2])` kategorik değişkene çevirdik. Yani bu sürekli değişkenleri sırasıyla 3,2,2 parçadan oluşacak hale getirdik. 

Bu en kötü dönüşümdür. Bunlar zaten veri setindeki en değerli değişkenlerdir bunları kategorik değişkene çevirip ölçeğini bozmak mantıklı değildir. Fakat bazen ilkel ağaç yöntemlerinde elinizdeki kategorik değişkenin sınıfları çok fazla olduğunda ya da sürekli değişkeninizin varyansı çok fazla olduğunda modelin çalışmasını hızlandırabilmek için sınıf sayısı azaltılabilmektedir. Fakat burada da bölme işlemlerini doğru yapabilmek için istatistiksel olarak incelemeler yaptıktan sonra işlem gerçekleştirilmelidir.

### Kategorik Değişkenler için Değişken Dönüşümü

Bu değişken dönüşümlerini bağımlı değişkenimiz için de yapıyoruz. Çünkü fonksiyonlar nümerik formatta istiyor bağımlı değişkeni.

#### <font color=green>İki Sınıflı Dönüşüm (1-0)</font>

İki sınıflı kategorik değişkenlerde bir sınıfa 0 bir sınıfa 1 diyoruz. 

In [17]:
import seaborn as sns
df = sns. load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

##### <font color=purple>Birinci yol</font>

In [9]:
from sklearn.preprocessing import LabelEncoder
df_l = df.copy()

lbe = LabelEncoder()
lbe.fit_transform(df_l["sex"])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

Şu anda veri setimizin içerisindeki cinsiyet değişkenini 1-0 olacak şekilde dönüştürme işlemini gerçekleştirdi. Ama veri setimizin orijinal halinde böyle bir değişken yok.

In [59]:
df_l.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Genelde bu yeni yapılan dönüştürme işlemini de veri setine eklemek gerekebiliyor. Bunun eski halini silmeden yeni bir değişken olarak atayabiliriz.

In [60]:
df_l["yeni_sex"] = lbe.fit_transform(df_l["sex"])

In [61]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         0
1       10.34  1.66    Male     No  Sun  Dinner     3         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0

##### <font color=purple>İkinci yol</font>

In [18]:
df_c = df.copy()

In [19]:
df_c ["yeni_sex"] = df_c["sex"].cat.codes

In [20]:
df_c.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1
1       10.34  1.66    Male     No  Sun  Dinner     3         0
2       21.01  3.50    Male     No  Sun  Dinner     3         0
3       23.68  3.31    Male     No  Sun  Dinner     2         0
4       24.59  3.61  Female     No  Sun  Dinner     4         1

Bu yöntemlerde çıkan sonuçta neye 1 neye 0 dendiğinin farkında olmamız gerekiyor.

#### <font color=green>Çok Sınıflı Dönüşüm (1 ve Diğerleri (0)) </font>

Örneğin veri setimizin içerisinde ikiden fazla sınıf var. Bu sınıflardan seçmiş olacağımız bir tanesine 1 diğerlerine 0 demek istiyoruz. Bunu özellikle çok sınıflı hedef değişkenimiz olduğunda, bunun bir tanesi ya da diğerleri şeklinde bir odaklanma ihtiyacı olduğunda bu dönüşümü kullanabiliyoruz.

In [ ]:
import seaborn as sns
df = sns. load_dataset('tips')
df.head()

In [22]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Buradaki "time" veya "day" değişkeni için böyle bir dönüştürme işlemi gerçekleştirilebiliriz.

In [23]:
import numpy as np

df["yeni_day"] = np.where(df["day"].str.contains("Sun"),1,0)

# day sütunu içerisindeki "Sun" değerlerini içeren gözlem birimlerine 1, 
# diğerlerine 0 ata ve bunu "yeni_day" sütununa kaydet.

In [24]:
df

total_bill   tip     sex smoker   day    time  size  yeni_day
0         16.99  1.01  Female     No   Sun  Dinner     2         1
1         10.34  1.66    Male     No   Sun  Dinner     3         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1
4         24.59  3.61  Female     No   Sun  Dinner     4         1
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0
242       17.82  1.75    Male     No   Sat  Dinner     2         0
243       18.78  3.00  Female     No  Thur  Dinner     2         0

[244 rows x 8 columns]

#### <font color=green>Çok Sınıflı Dönüşüm (Her bir sınıfa nümerik değer atama)</font>

Diğerlerinde olduğu gibi bir kategorik değişkene sahip olduğu sınıflar sayılara dönüştürülür. Yani örneğin 4 sınıf varsa bunlar farklı farklı isimlendirmelere sahipse 1,2,3,4 olacak şekilde dönüştürülebilir. Eğer sınıflar arasında bir sıralama yoksa bu dönüşüm işlemi tavsiye edilmez.

In [ ]:
import seaborn as sns
df = sns. load_dataset('tips')
df.head()

In [25]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [26]:
lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

#### <font color=green>One-Hot Encoding (Her bir sınıf için yeni değişkenler oluşturma)</font>

Kagegorik değişkeni nümerik hale dönüştürmek için çoğu zaman bu yaklaşımı kullanacağız. One-hot encoding sayesinde hem verilerimizi nümerik hale dönüştürmüş oluyoruz hem de sınıfların etkisini veri setinde hissettirilir hale getiriyoruz.

`pd.get_dummies()` fonksiyonuyla gerçekleştirdiğimiz one-hot encoding, işlemi gerçekleştirdiğimiz değişkende sınıf sayısı kadar yeni değişken oluşturur. Eski değişkende yer alan değerlere göre 1-0 ataması yapar. 

In [42]:
import seaborn as sns
df = sns. load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [45]:
import pandas as pd

df_one_hot = pd.get_dummies(df, columns = ["sex"], prefix = ["sex"]) 
df_one_hot.head()

total_bill   tip smoker  day    time  size  sex_Male  sex_Female
0       16.99  1.01     No  Sun  Dinner     2         0           1
1       10.34  1.66     No  Sun  Dinner     3         1           0
2       21.01  3.50     No  Sun  Dinner     3         1           0
3       23.68  3.31     No  Sun  Dinner     2         1           0
4       24.59  3.61     No  Sun  Dinner     4         0           1

Elimizdeki iki sınıflı kategorik değişkenin sınıf sayısı kadar yeni değişken oluştu ve oluşmuş olan bu yeni değişkenler de 1-0 olarak tanımlanmış oldu. Eski 'sex' değişkeni de silinmiş oldu. Bu değişkeni ekleyerek durumu inceleyelim.

In [46]:
df_e = pd.concat([df_one_hot, df["sex"]],axis=1)

df_e.head()

total_bill   tip smoker  day    time  size  sex_Male  sex_Female     sex
0       16.99  1.01     No  Sun  Dinner     2         0           1  Female
1       10.34  1.66     No  Sun  Dinner     3         1           0    Male
2       21.01  3.50     No  Sun  Dinner     3         1           0    Male
3       23.68  3.31     No  Sun  Dinner     2         1           0    Male
4       24.59  3.61     No  Sun  Dinner     4         0           1  Female

Burada bakacak olursak eğer cinsiyet female ise sex_Female'in 1 sex_Male'in 0, cinsiyet male ise sex_Male'in 1 sex_Female'in 0 olduğunu görüyoruz.

Burada dummy değişken tuzağı dediğimiz bir durum söz konusu. Bu dönüşümü uyguladığımızda oluşan yeni değişkenler birbirleri üzerinden oluşturulabiliyorsa bu durum dummy değişken tuzağı olarak adlandırılır. Çünkü örneğin female'in 0 olması male'in 1 olması anlamına gelir. Bu durumdan kaçınmak için her zaman oluşan yeni değişkenlerden 1 tanesini dataframe'den atmamız gerekiyor (ilk değişkeni fonksiyon zaten atmıştı). 

In [47]:
pd.get_dummies(df, columns = ["day"], prefix = ["day"]).head()

total_bill   tip     sex smoker    time  size  day_Thur  day_Fri  day_Sat  \
0       16.99  1.01  Female     No  Dinner     2         0        0        0   
1       10.34  1.66    Male     No  Dinner     3         0        0        0   
2       21.01  3.50    Male     No  Dinner     3         0        0        0   
3       23.68  3.31    Male     No  Dinner     2         0        0        0   
4       24.59  3.61  Female     No  Dinner     4         0        0        0   

   day_Sun  
0        1  
1        1  
2        1  
3        1  
4        1

In [48]:
df['day'].unique()

[Sun, Sat, Thur, Fri]
Categories (4, object): [Sun, Sat, Thur, Fri]

10 yeni değişken oluştu diyelim 1 tanesini silmemiz ve 9 tanesiyle devam etmemiz gerekir.

##### <font color=purple>Birinci yol</font>

**Tüm dataframe'i one-hot encoding yapmak istediğimiz değişkeni belirterek `pd.get_dummies()` fonksiyonuna sokuyoruz.**

In [32]:
import pandas as pd
df_one_hot = pd.get_dummies(df, columns = ["sex"], prefix = ["sex"]) 

# prefix yeni değişkenlerin ön adı.

In [33]:
df_one_hot.head()

total_bill   tip smoker  day    time  size  sex_Male  sex_Female
0       16.99  1.01     No  Sun  Dinner     2         0           1
1       10.34  1.66     No  Sun  Dinner     3         1           0
2       21.01  3.50     No  Sun  Dinner     3         1           0
3       23.68  3.31     No  Sun  Dinner     2         1           0
4       24.59  3.61     No  Sun  Dinner     4         0           1

**'sex' değişkeni ortadan kalktı. İhtiyaç halinde yeniden eklenebilir.**

In [34]:
df_c = pd.concat([df_one_hot,df["sex"]],axis=1)

df_c.head()

total_bill   tip smoker  day    time  size  sex_Male  sex_Female     sex
0       16.99  1.01     No  Sun  Dinner     2         0           1  Female
1       10.34  1.66     No  Sun  Dinner     3         1           0    Male
2       21.01  3.50     No  Sun  Dinner     3         1           0    Male
3       23.68  3.31     No  Sun  Dinner     2         1           0    Male
4       24.59  3.61     No  Sun  Dinner     4         0           1  Female

**sex_Male ve sex_Female aynı durumu ifade ettiği için bir tanesini ortadan kaldırıyoruz.**

In [35]:
df_y = df_one_hot.drop(['sex_Male'], axis=1)

df_y.head()

total_bill   tip smoker  day    time  size  sex_Female
0       16.99  1.01     No  Sun  Dinner     2           1
1       10.34  1.66     No  Sun  Dinner     3           0
2       21.01  3.50     No  Sun  Dinner     3           0
3       23.68  3.31     No  Sun  Dinner     2           0
4       24.59  3.61     No  Sun  Dinner     4           1

##### <font color=purple>İkinci yol</font>

**Sadece one-hot encoding yapmak istediğimiz değişkeni `pd.get_dummies()` fonksiyonuna sokuyoruz.**

In [39]:
df_one_hot_encoding = pd.get_dummies(df['sex'], prefix="sex")

df_one_hot_encoding.head()

sex_Male  sex_Female
0         0           1
1         1           0
2         1           0
3         1           0
4         0           1

**Kendi dataframe'imize bu dataframe'i ekliyoruz.**

In [40]:
df_co = pd.concat([df, df_one_hot_encoding], axis=1)
df_co.head()

total_bill   tip     sex smoker  day    time  size  sex_Male  sex_Female
0       16.99  1.01  Female     No  Sun  Dinner     2         0           1
1       10.34  1.66    Male     No  Sun  Dinner     3         1           0
2       21.01  3.50    Male     No  Sun  Dinner     3         1           0
3       23.68  3.31    Male     No  Sun  Dinner     2         1           0
4       24.59  3.61  Female     No  Sun  Dinner     4         0           1

**Bilgilerin korele olmasını engellemek için hem 'sex' hem de 'sex_Male' değişkenlerini siliyoruz.**

In [41]:
df_yo = df_co.drop(["sex","sex_Male"], axis=1)

df_yo.head()

total_bill   tip smoker  day    time  size  sex_Female
0       16.99  1.01     No  Sun  Dinner     2           1
1       10.34  1.66     No  Sun  Dinner     3           0
2       21.01  3.50     No  Sun  Dinner     3           0
3       23.68  3.31     No  Sun  Dinner     2           0
4       24.59  3.61     No  Sun  Dinner     4           1