<font color='green'> 
**Udemy - (50 Saat) Python A-Z™: Veri Bilimi ve Machine Learning**
7. Bölüm - Veri Bilimi İçin İstatistik (179. video) - Vahit Keskin anlattı. </font>

# Örnek Teorisi Uygulama

Varsayalım ki bir ilçedeki kişilerin yaşlarına ilişkin bir çıkarımda bulunmak istiyoruz. Bu ilçedeki kişilerin yaş ortalamasını merak ediyoruz. Ama bu ilçede 10.000 kişi yaşıyor ve bu 10 bin kişinin her birisiyle gidip tek tek görüşüp bunun ortalamasını almak çok da mümkün değil. Bunun yerine bunun içerisinde 100 kişilik örneklem çekip bu 100 kişinin yaş ortalamasını inceleyip bu ilçeyle alakalı yaş ortalamasının ne olacağını tahmin etmek istiyoruz. 

### Populasyon Oluşturma

In [1]:
import numpy as np
populasyon = np.random.randint(0, 80, 10000) 
# 0 ile 80 yaş arasında 10.000 tane kişi olacak şekilde populasyon oluşturuyoruz.

In [2]:
populasyon

array([63, 70, 25, ..., 21,  7, 14])

In [3]:
populasyon[0:10]

array([63, 70, 25, 36, 46, 62, 49, 34, 32, 13])

### Örneklem Çekimi

Pythonda örneklem çekmek için kullanılabilecek birçok yaklaşım var. Bizim burada ele alacak olduğumuz numpy'ın içerisindeki random fonksiyonu. Bunun öncesinde bir seed ayarı yapmamız lazım. Bu, yapılacak olan işlemlerin her tekrar edildiğinde aynı sonuçları getirmesini garanti altına alan bir işlem. `np.random.seed(115)` dediğimde mesela bir yapıya göre örnek çekecek. Daha sonra bir daha çekmek istediğinde yine aynı yapıya göre çekecek. Ama eğer buraya random.seed'i koymazsam her fonksiyonu tekrar çalıştırdığında farklı örneklemler çekmiş olacak.

*np.random.seed() yazmazsak her çalıştırdığımızda farklı sonuçlar üretiyor.*

In [5]:
orneklem = np.random.choice(a = populasyon, size = 100) 
orneklem[0:10] 

array([26, 23, 21, 61,  2, 10,  0, 59, 70, 28])

*np.random.seed() yazıp devam ediyoruz.*

In [4]:
np.random.seed(115)
orneklem = np.random.choice(a = populasyon, size = 100) 
# populasyonun içerisinden rastgele 100 tane örnek çek.

orneklem[0:10] 
# hep aynı sonuçları üretiyor.

array([39, 16, 35, 57, 50, 10, 40, 69,  7, 59])

Şu anda populasyonumuz içerisinden 100 tane gözlemi rastgele alacak şekilde çektik. Bunun ortalaması nedir diye bakıyoruz.

In [6]:
orneklem.mean()

42.99

Populasyonun ortalaması nedir?

In [7]:
populasyon.mean()

39.8104

Örneklemin ve populasyonun ortalaması birbirine çok yakın. Bu, örneklem teorisinin gücünü ifade ediyor. Bunun üzerine bazı istatistiksel yorumlar yapacağız ileride. Diyeceğiz ki %95 güvenilirlik ile bu ortalama şu değerle şu değer arasındadır dediğimizde artık bilimsel anlamda belirli bir güven düzeyi de vererek elde ettiğimiz bu örnek üzerinden olan istatistikleri daha bilimsel, daha güvenilir bir şekilde yorumlayabiliyor olacağız. 

### Örneklem Dağılımı

Ben bu populasyon içerisinden rastgele 100 tane örnek çektim. Yani bir tane örneklem çektim. Peki hangi 100 taneyi çekmiş oldum? Ya farklı bir 100'lük gelseydi? Buna yönelik olarak farklı farklı örneklemler çekeceğiz. Yani örneklemlerin artık dağılımı elimizde olmuş olacak. 

In [8]:
np.random.seed(10)
orneklem1 = np.random.choice(a = populasyon, size = 100)
orneklem2 = np.random.choice(a = populasyon, size = 100)
orneklem3 = np.random.choice(a = populasyon, size = 100)
orneklem4 = np.random.choice(a = populasyon, size = 100)
orneklem5 = np.random.choice(a = populasyon, size = 100)
orneklem6 = np.random.choice(a = populasyon, size = 100)
orneklem7 = np.random.choice(a = populasyon, size = 100)
orneklem8 = np.random.choice(a = populasyon, size = 100)
orneklem9 = np.random.choice(a = populasyon, size = 100)
orneklem10 = np.random.choice(a = populasyon, size = 100)

Elimizdeki bu bütün örneklemlerin her birinin ortalamasını alıp bunların da ortalamasını alacağız.

In [9]:
(orneklem1.mean() + orneklem2.mean() + orneklem3.mean() + orneklem4.mean() + orneklem5.mean() 
+ orneklem6.mean() + orneklem7.mean() + orneklem8.mean() + orneklem9.mean() + orneklem10.mean() )  / 10

40.222

Bu değer populasyon.mean()'ine daha yakın. 

In [10]:
populasyon.mean()

39.8104

In [11]:
orneklem1.mean()

41.18

In [12]:
orneklem2.mean()

40.44

Birçok örneklemin farklı değeri var şu an elimizde. Bunların hepsinin ortalamasını alırsak teorik olarak "merkezi limit teoremi" aracılığıyla populasyon ortalamasına gitmiş oluyoruz. 